sudo: false
language: python
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
    - gfortran
    - g++
cache:
  directories:
  - $HOME/miniconda
  - $HOME/miniconda3
  - $HOME/mpich_install
  - $HOME/hdf5_install
  - $HOME/phdf5_install

before_install:
  # Handle Python third-party packages
  - ./scripts/travis/setup_conda.sh

  # Install GCC, MPICH, HDF5, PHDF5
  - ./scripts/travis/install_dependencies.sh
  - export FC=gfortran
  - export MPI_DIR=$HOME/mpich_install
  - export PHDF5_DIR=$HOME/phdf5_install
  - export HDF5_DIR=$HOME/hdf5_install

install: true

before_script:
  - cd data
  - git clone --branch=master git://github.com/bhermanmit/nndc_xs nndc_xs
  - cat nndc_xs/nndc.tar.gza* | tar xzvf -
  - rm -rf nndc_xs
  - export CROSS_SECTIONS=$PWD/nndc/cross_sections.xml
  - cd ..

script:
  - cd tests
  - export OMP_NUM_THREADS=3
  - ./travis.sh
  - cd ..
