#include <cmath>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>

#include "openmc/constants.h"
#include "openmc/particle_type.h"
#include "openmc/random_lcg.h"
#include "openmc/recoil.h"

using namespace openmc;
using Catch::Approx;

//==============================================================================
// The shared kinematic fixture
//
// tests/cpp_unit_tests/data/kinematics_fixture.txt is generated by
// `python -m recoil.fixtures` in the jnm-recoil analysis repository, which
// holds the other implementation of the contract in recoil/kinematics.py. Both
// must reproduce it, which is what makes them one contract rather than two
// similar ones. Regenerate it whenever the contract changes; do not edit it.
//==============================================================================

namespace {

//! Values are written to 13 significant figures, so this is what the two
//! implementations are required to agree to. Bit-exactness is not the goal.
constexpr double FIXTURE_TOLERANCE = 1.0e-11;

//! Absolute floor on the agreement, in eV. Every quantity here is a difference
//! of much larger ones -- U0 cancels two numbers of order E_in near threshold,
//! and Q cancels four mass excesses of order 1e7 eV -- so below this the two
//! implementations are being asked for digits neither has. One millielectron
//! volt is ten orders below the accuracy of the mass table itself.
constexpr double FIXTURE_FLOOR_EV = 1.0e-3;

//! Relative in the value and in the incident energy, with that floor.
bool agrees(double actual, double expected, double e_in)
{
  return std::abs(actual - expected) <=
         std::max(
           FIXTURE_TOLERANCE * std::max(std::abs(expected), std::abs(e_in)),
           FIXTURE_FLOOR_EV);
}

struct FixtureMass {
  int z, a;
  double mass;
};

struct FixtureCase {
  std::string name;
  int z_t, a_t, n_emitted;
  double e_in;
  recoil::AtomicNumbers emitted[3];
  recoil::AtomicNumbers ion;
  double q, u0, e_event, e_shape, e_x;
};

struct Fixture {
  std::vector<FixtureMass> masses;
  std::vector<FixtureCase> cases;
  bool found {false};
};

Fixture read_fixture()
{
  Fixture out;
  std::ifstream in(
    std::string(OPENMC_UNIT_TEST_DATA_DIR) + "/kinematics_fixture.txt");
  if (!in)
    return out;
  out.found = true;

  std::string line;
  while (std::getline(in, line)) {
    if (line.empty() || line[0] == '#')
      continue;
    std::istringstream s(line);
    std::string tag;
    s >> tag;
    if (tag == "MASS") {
      FixtureMass m;
      s >> m.z >> m.a >> m.mass;
      out.masses.push_back(m);
    } else if (tag == "CASE") {
      FixtureCase c;
      s >> c.name >> c.z_t >> c.a_t >> c.e_in >> c.n_emitted;
      for (int i = 0; i < 3; ++i)
        s >> c.emitted[i].Z >> c.emitted[i].A;
      s >> c.ion.Z >> c.ion.A >> c.q >> c.u0 >> c.e_event >> c.e_shape >> c.e_x;
      out.cases.push_back(c);
    }
  }
  return out;
}

} // namespace

TEST_CASE("Kinematic contract: masses agree with the Python implementation")
{
  Fixture fx = read_fixture();
  REQUIRE(fx.found);
  REQUIRE(fx.masses.size() > 50);

  for (const auto& m : fx.masses) {
    double got = recoil::nuclear_mass_ev({m.z, m.a});
    INFO("Z=" << m.z << " A=" << m.a);
    REQUIRE(got > 0.0);
    REQUIRE(agrees(got, m.mass, m.mass));
  }
}

TEST_CASE("Kinematic contract: budgets and endpoints agree with Python")
{
  Fixture fx = read_fixture();
  REQUIRE(fx.found);
  REQUIRE(fx.cases.size() > 200);

  for (const auto& c : fx.cases) {
    INFO(c.name << " at E_in = " << c.e_in << " eV");

    bool ok = false;
    double q =
      recoil::mass_difference_q({c.z_t, c.a_t}, c.emitted, c.n_emitted, ok);
    REQUIRE(ok);
    REQUIRE(agrees(q, c.q, c.e_in));

    double m_t = recoil::nuclear_mass_ev({c.z_t, c.a_t});
    double u0 = recoil::entrance_internal_energy(c.e_in, m_t, q);
    REQUIRE(agrees(u0, c.u0, c.e_in));

    // event endpoint: every other product is charged to the budget at rest, so
    // the ion recoils against the daughter plus the rest
    recoil::AtomicNumbers daughter {c.z_t, c.a_t + 1};
    double rest = 0.0;
    bool used_ion = false;
    for (int i = 0; i < c.n_emitted; ++i) {
      daughter.Z -= c.emitted[i].Z;
      daughter.A -= c.emitted[i].A;
      bool is_probe =
        !used_ion && c.emitted[i].Z == c.ion.Z && c.emitted[i].A == c.ion.A;
      if (is_probe)
        used_ion = true;
      else
        rest += recoil::nuclear_mass_ev(c.emitted[i]);
    }
    double m_b = recoil::nuclear_mass_ev(c.ion);
    double m_d = recoil::nuclear_mass_ev(daughter) + rest;
    REQUIRE(agrees(recoil::two_body_endpoint(u0, m_b, m_d), c.e_event, c.e_in));

    REQUIRE(agrees(recoil::residual_excitation(u0, 0.5 * c.e_event, m_b, m_d),
      c.e_x, c.e_in));

    if (!(c.ion.Z == 0 && c.ion.A == 1)) {
      REQUIRE(agrees(recoil::shape_endpoint(c.e_in, {c.z_t, c.a_t}, c.ion),
        c.e_shape, c.e_in));
    }
  }
}

TEST_CASE("Kinematic contract: invariants hold independently of the fixture")
{
  // These would still have to hold if every stored number were wrong.
  const recoil::AtomicNumbers alpha {2, 4}, proton {1, 1}, neutron {0, 1};

  SECTION("an inelastic channel releases nothing")
  {
    for (auto target : {recoil::AtomicNumbers {6, 12}, {26, 56}, {82, 208}}) {
      bool ok = false;
      double q = recoil::mass_difference_q(target, &neutron, 1, ok);
      REQUIRE(ok);
      REQUIRE(std::abs(q) < 1.0e-3);
    }
  }

  SECTION("the entrance correction is what E_in + Q leaves out")
  {
    double m_t = recoil::nuclear_mass_ev({26, 56});
    double m_n = MASS_NEUTRON * AMU_EV;
    double u = recoil::entrance_internal_energy(14.0e6, m_t, -2.0e6);
    REQUIRE(u < 14.0e6 - 2.0e6);
    REQUIRE((14.0e6 - 2.0e6) - u ==
            Approx(14.0e6 * m_n / (m_t + m_n)).epsilon(1e-12));
  }

  SECTION("no excitation is left at the endpoint")
  {
    double m_b = recoil::nuclear_mass_ev(alpha);
    double m_d = recoil::nuclear_mass_ev({24, 53});
    double u = 9.0e6;
    double e_max = recoil::two_body_endpoint(u, m_b, m_d);
    REQUIRE(std::abs(recoil::residual_excitation(u, e_max, m_b, m_d)) < 1.0e-6);
  }

  SECTION("a missing mass is reported, not invented")
  {
    REQUIRE(recoil::nuclear_mass_ev({60, 300}) == 0.0);
    bool ok = true;
    recoil::mass_difference_q({60, 300}, &proton, 1, ok);
    REQUIRE_FALSE(ok);
    // an impossible daughter is caught too
    ok = true;
    recoil::AtomicNumbers many[3] = {alpha, alpha, alpha};
    recoil::mass_difference_q({2, 4}, many, 3, ok);
    REQUIRE_FALSE(ok);
  }

  SECTION("the triton is the nucleus, not the H-3 atom")
  {
    // ATOMIC_MASS holds the atomic H-3 mass at this PDG number, so a plain
    // table lookup would be 0.55 mu -- 511 keV -- too heavy.
    double triton = recoil::nuclear_mass_ev({1, 3});
    REQUIRE(triton / AMU_EV == Approx(3.0155007).epsilon(1e-7));
    REQUIRE(triton / AMU_EV < 3.0160);
  }
}

TEST_CASE("Recoil particle masses")
{
  // Masses come from the tabulated atomic masses, in eV
  REQUIRE(recoil::particle_mass_ev(ParticleType::photon()) == 0.0);
  REQUIRE(recoil::particle_mass_ev(ParticleType::neutron()) ==
          Approx(MASS_NEUTRON_EV).epsilon(1e-9));
  REQUIRE(recoil::particle_mass_ev(ParticleType::alpha()) / AMU_EV ==
          Approx(4.0015).epsilon(1e-4));

  // A nuclide that is not in the tabulated mass table still gets a usable mass
  double m = recoil::particle_mass_ev(ParticleType {40, 130, 0});
  REQUIRE(m > 0.0);
  REQUIRE(m / AMU_EV == Approx(130.0).epsilon(0.02));
}

TEST_CASE("Light-ion emission spectrum")
{
  // Alpha emission leaving Cr-53: the spectrum must vanish at both ends, be
  // strongly suppressed well below the Coulomb barrier, and integrate to a mean
  // that sits above the barrier.
  const double E_max = 13.3e6;
  const int Z_b = 2, A_b = 4, Z_d = 24, A_d = 53;

  REQUIRE(recoil::light_ion_pdf(0.0, E_max, Z_b, A_b, Z_d, A_d) == 0.0);
  REQUIRE(recoil::light_ion_pdf(E_max, E_max, Z_b, A_b, Z_d, A_d) == 0.0);
  REQUIRE(recoil::light_ion_pdf(2.0e6, E_max, Z_b, A_b, Z_d, A_d) <
          0.01 * recoil::light_ion_pdf(9.0e6, E_max, Z_b, A_b, Z_d, A_d));

  // Neutral light ions feel no barrier, so the spectrum is
  // E*(1 - E/E_max)^nu with nu the calibrated endpoint exponent. Written
  // against LightIonParams rather than a hardcoded exponent so that a refit
  // does not silently break a test whose subject is the barrier, not nu.
  const recoil::LightIonParams deployed {};
  double neutral = recoil::light_ion_pdf(0.5 * E_max, E_max, 0, 1, Z_d, A_d);
  REQUIRE(
    neutral == Approx(0.5 * E_max * std::pow(0.5, deployed.nu)).epsilon(1e-12));

  SECTION("sampling reproduces the spectrum mean")
  {
    uint64_t seed = 1;
    const int N = 200000;
    double sum = 0.0;
    double max_sampled = 0.0;
    for (int i = 0; i < N; ++i) {
      double E = recoil::sample_light_ion_energy(
        E_max, E_max, Z_b, A_b, Z_d, A_d, &seed);
      REQUIRE(E >= 0.0);
      REQUIRE(E <= E_max);
      sum += E;
      max_sampled = std::max(max_sampled, E);
    }
    double sampled_mean = sum / N;

    // Reference mean by direct quadrature of the same pdf
    const int NQ = 200000;
    double num = 0.0, den = 0.0;
    for (int i = 0; i < NQ; ++i) {
      double E = E_max * (i + 0.5) / NQ;
      double f = recoil::light_ion_pdf(E, E_max, Z_b, A_b, Z_d, A_d);
      num += f * E;
      den += f;
    }
    REQUIRE(sampled_mean == Approx(num / den).epsilon(0.01));
    REQUIRE(max_sampled > 0.9 * E_max);
  }

  SECTION("truncation restricts the sample to the energy budget")
  {
    uint64_t seed = 7;
    const double E_limit = 4.0e6;
    for (int i = 0; i < 20000; ++i) {
      double E = recoil::sample_light_ion_energy(
        E_max, E_limit, Z_b, A_b, Z_d, A_d, &seed);
      REQUIRE(E <= E_limit);
      REQUIRE(E >= 0.0);
    }
  }
}

TEST_CASE("Light-ion spectrum: parameterized overload matches the deployed one")
{
  // The parameterized overload exists so that candidate parameter sets can be
  // scored against evaluated data through the same code path the transport
  // kernel uses, rather than against a reimplementation in the fitting
  // scripts. That is only worth anything if the default-constructed parameters
  // reproduce the fixed constants bit for bit.
  const recoil::LightIonParams deployed {};
  for (int Z_b : {1, 2}) {
    for (int A_b : {1, 4}) {
      for (int Z_d : {6, 26, 74}) {
        int A_d = 2 * Z_d + 2;
        double E_max = 12.0e6;
        for (double frac : {0.01, 0.1, 0.35, 0.5, 0.75, 0.95, 0.999}) {
          double E = frac * E_max;
          REQUIRE(
            recoil::light_ion_pdf(E, E_max, Z_b, A_b, Z_d, A_d) ==
            recoil::light_ion_pdf(E, E_max, Z_b, A_b, Z_d, A_d, deployed));
        }
      }
    }
  }
}

TEST_CASE("Light-ion spectrum: the endpoint exponent behaves as expected")
{
  // nu is 0.5 in the deployed model and 1.21 in the refit. A larger exponent
  // must soften the spectrum, i.e. lower its mean, or the refit result is
  // being read with the wrong sign.
  auto mean_of = [](double nu) {
    recoil::LightIonParams par {1.8, 0.8e6, nu};
    const int N = 4000;
    double E_max = 10.0e6, num = 0.0, den = 0.0, prev_f = 0.0, prev_E = 0.0;
    for (int i = 0; i <= N; ++i) {
      double E = E_max * i / N;
      double f = recoil::light_ion_pdf(E, E_max, 1, 1, 26, 56, par);
      if (i > 0) {
        num += 0.5 * (f * E + prev_f * prev_E) * (E - prev_E);
        den += 0.5 * (f + prev_f) * (E - prev_E);
      }
      prev_f = f;
      prev_E = E;
    }
    return num / den;
  };
  double m_half = mean_of(0.5);
  double m_soft = mean_of(1.211);
  REQUIRE(m_soft < m_half);
  // and nu = 0.5 must agree with the std::sqrt fast path used for it
  REQUIRE(mean_of(0.5) == Approx(m_half).epsilon(1e-12));
}

TEST_CASE("Light-ion sampler realizes the parameterized spectrum")
{
  // Only checkable in C++: the sampler draws by rejection against a scanned
  // envelope, so a change in the spectrum's shape could in principle break the
  // envelope without changing the PDF at all.
  for (double nu : {0.5, 1.211}) {
    recoil::LightIonParams par {1.8, 0.8e6, nu};
    double E_max = 9.0e6;
    const int N = 3000;
    double num = 0.0, den = 0.0, prev_f = 0.0, prev_E = 0.0;
    for (int i = 0; i <= N; ++i) {
      double E = E_max * i / N;
      double f = recoil::light_ion_pdf(E, E_max, 2, 4, 24, 52, par);
      if (i > 0) {
        num += 0.5 * (f * E + prev_f * prev_E) * (E - prev_E);
        den += 0.5 * (f + prev_f) * (E - prev_E);
      }
      prev_f = f;
      prev_E = E;
    }
    double analytic = num / den;

    uint64_t seed = 987654321ULL;
    const int n_draw = 200000;
    double acc = 0.0;
    for (int i = 0; i < n_draw; ++i)
      acc +=
        recoil::sample_light_ion_energy(E_max, E_max, 2, 4, 24, 52, &seed, par);
    REQUIRE(acc / n_draw == Approx(analytic).epsilon(0.02));
  }
}
