#include <algorithm>
#include <cmath>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>

#include "openmc/constants.h"
#include "openmc/endf.h"
#include "openmc/particle_type.h"
#include "openmc/random_dist.h"
#include "openmc/random_lcg.h"
#include "openmc/recoil.h"

using namespace openmc;
using Catch::Approx;

//==============================================================================
// The shared kinematic fixture
//
// tests/cpp_unit_tests/data/kinematics_fixture.txt is generated by
// `python -m recoil.fixtures` in the jnm-recoil analysis repository, which
// holds the other implementation of the contract in recoil/kinematics.py. Both
// must reproduce it, which is what makes them one contract rather than two
// similar ones. Regenerate it whenever the contract changes; do not edit it.
//==============================================================================

namespace {

//! Values are written to 13 significant figures, so this is what the two
//! implementations are required to agree to. Bit-exactness is not the goal.
constexpr double FIXTURE_TOLERANCE = 1.0e-11;

//! Absolute floor on the agreement, in eV. Every quantity here is a difference
//! of much larger ones -- U0 cancels two numbers of order E_in near threshold,
//! and Q cancels four mass excesses of order 1e7 eV -- so below this the two
//! implementations are being asked for digits neither has. One millielectron
//! volt is ten orders below the accuracy of the mass table itself.
constexpr double FIXTURE_FLOOR_EV = 1.0e-3;

//! Relative in the value and in the incident energy, with that floor.
bool agrees(double actual, double expected, double e_in)
{
  return std::abs(actual - expected) <=
         std::max(
           FIXTURE_TOLERANCE * std::max(std::abs(expected), std::abs(e_in)),
           FIXTURE_FLOOR_EV);
}

//! Ordinary-density view of the logarithmic spectrum used by transport
double light_ion_pdf(double E, double E_max, int Z_b, int A_b, int Z_d, int A_d,
  const recoil::LightIonParams& par = {})
{
  return std::exp(recoil::light_ion_log_pdf(E, E_max, Z_b, A_b, Z_d, A_d, par));
}

struct FixtureMass {
  int z, a;
  double mass;
};

struct FixtureCase {
  std::string name;
  int z_t, a_t, n_emitted;
  double e_in;
  recoil::NuclearNumbers emitted[3];
  recoil::NuclearNumbers ion;
  double q, u0, e_event, e_shape, e_x;
};

struct FixtureLogPdf {
  int z_b, a_b, z_d, a_d;
  double e_max, e, log_p;
};

struct Fixture {
  std::vector<FixtureMass> masses;
  std::vector<FixtureCase> cases;
  std::vector<FixtureLogPdf> log_pdf;
  bool found {false};
};

Fixture read_fixture()
{
  Fixture out;
  std::ifstream in("kinematics_fixture.txt");
  if (!in)
    return out;
  out.found = true;

  std::string line;
  while (std::getline(in, line)) {
    if (line.empty() || line[0] == '#')
      continue;
    std::istringstream s(line);
    std::string tag;
    s >> tag;
    if (tag == "MASS") {
      FixtureMass m;
      s >> m.z >> m.a >> m.mass;
      out.masses.push_back(m);
    } else if (tag == "LOGPDF") {
      FixtureLogPdf r;
      s >> r.z_b >> r.a_b >> r.z_d >> r.a_d >> r.e_max >> r.e >> r.log_p;
      out.log_pdf.push_back(r);
    } else if (tag == "CASE") {
      FixtureCase c;
      s >> c.name >> c.z_t >> c.a_t >> c.e_in >> c.n_emitted;
      for (int i = 0; i < 3; ++i)
        s >> c.emitted[i].Z >> c.emitted[i].A;
      s >> c.ion.Z >> c.ion.A >> c.q >> c.u0 >> c.e_event >> c.e_shape >> c.e_x;
      out.cases.push_back(c);
    }
  }
  return out;
}

} // namespace

TEST_CASE("ENDF recoil exit channels")
{
  auto check = [](int mt, ExitChannel expected) {
    auto channel = reaction_exit_channel(mt);
    REQUIRE(channel.has_value());
    CHECK(channel->neutron == expected.neutron);
    CHECK(channel->proton == expected.proton);
    CHECK(channel->deuteron == expected.deuteron);
    CHECK(channel->triton == expected.triton);
    CHECK(channel->he3 == expected.he3);
    CHECK(channel->alpha == expected.alpha);
  };

  check(ELASTIC, {1});
  check(N_N1, {1});
  check(N_NC, {1});
  check(N_2N0, {2});
  check(N_2NC, {2});
  check(N_P0, {0, 1});
  check(N_PC, {0, 1});
  check(N_D0, {0, 0, 1});
  check(N_DC, {0, 0, 1});
  check(N_T0, {0, 0, 0, 1});
  check(N_TC, {0, 0, 0, 1});
  check(N_3HE0, {0, 0, 0, 0, 1});
  check(N_3HEC, {0, 0, 0, 0, 1});
  check(N_A0, {0, 0, 0, 0, 0, 1});
  check(N_AC, {0, 0, 0, 0, 0, 1});

  struct Case {
    int mt;
    ExitChannel channel;
  };
  const Case cases[] = {
    {N_2ND, {2, 0, 1}},
    {N_2N, {2}},
    {N_3N, {3}},
    {N_NA, {1, 0, 0, 0, 0, 1}},
    {N_N3A, {1, 0, 0, 0, 0, 3}},
    {N_2NA, {2, 0, 0, 0, 0, 1}},
    {N_3NA, {3, 0, 0, 0, 0, 1}},
    {N_NP, {1, 1}},
    {N_N2A, {1, 0, 0, 0, 0, 2}},
    {N_2N2A, {2, 0, 0, 0, 0, 2}},
    {N_ND, {1, 0, 1}},
    {N_NT, {1, 0, 0, 1}},
    {N_N3HE, {1, 0, 0, 0, 1}},
    {N_ND2A, {1, 0, 1, 0, 0, 2}},
    {N_NT2A, {1, 0, 0, 1, 0, 2}},
    {N_4N, {4}},
    {N_2NP, {2, 1}},
    {N_3NP, {3, 1}},
    {N_N2P, {1, 2}},
    {N_NPA, {1, 1, 0, 0, 0, 1}},
    {N_GAMMA, {}},
    {N_P, {0, 1}},
    {N_D, {0, 0, 1}},
    {N_T, {0, 0, 0, 1}},
    {N_3HE, {0, 0, 0, 0, 1}},
    {N_A, {0, 0, 0, 0, 0, 1}},
    {N_2A, {0, 0, 0, 0, 0, 2}},
    {N_3A, {0, 0, 0, 0, 0, 3}},
    {N_2P, {0, 2}},
    {N_PA, {0, 1, 0, 0, 0, 1}},
    {N_T2A, {0, 0, 0, 1, 0, 2}},
    {N_D2A, {0, 0, 1, 0, 0, 2}},
    {N_PD, {0, 1, 1}},
    {N_PT, {0, 1, 0, 1}},
    {N_DA, {0, 0, 1, 0, 0, 1}},
    {N_5N, {5}},
    {N_6N, {6}},
    {N_2NT, {2, 0, 0, 1}},
    {N_TA, {0, 0, 0, 1, 0, 1}},
    {N_4NP, {4, 1}},
    {N_3ND, {3, 0, 1}},
    {N_NDA, {1, 0, 1, 0, 0, 1}},
    {N_2NPA, {2, 1, 0, 0, 0, 1}},
    {N_7N, {7}},
    {N_8N, {8}},
    {N_5NP, {5, 1}},
    {N_6NP, {6, 1}},
    {N_7NP, {7, 1}},
    {N_4NA, {4, 0, 0, 0, 0, 1}},
    {N_5NA, {5, 0, 0, 0, 0, 1}},
    {N_6NA, {6, 0, 0, 0, 0, 1}},
    {N_7NA, {7, 0, 0, 0, 0, 1}},
    {N_4ND, {4, 0, 1}},
    {N_5ND, {5, 0, 1}},
    {N_6ND, {6, 0, 1}},
    {N_3NT, {3, 0, 0, 1}},
    {N_4NT, {4, 0, 0, 1}},
    {N_5NT, {5, 0, 0, 1}},
    {N_6NT, {6, 0, 0, 1}},
    {N_2N3HE, {2, 0, 0, 0, 1}},
    {N_3N3HE, {3, 0, 0, 0, 1}},
    {N_4N3HE, {4, 0, 0, 0, 1}},
    {N_3N2P, {3, 2}},
    {N_3N2A, {3, 0, 0, 0, 0, 2}},
    {N_3NPA, {3, 1, 0, 0, 0, 1}},
    {N_DT, {0, 0, 1, 1}},
    {N_NPD, {1, 1, 1}},
    {N_NPT, {1, 1, 0, 1}},
    {N_NDT, {1, 0, 1, 1}},
    {N_NP3HE, {1, 1, 0, 0, 1}},
    {N_ND3HE, {1, 0, 1, 0, 1}},
    {N_NT3HE, {1, 0, 0, 1, 1}},
    {N_NTA, {1, 0, 0, 1, 0, 1}},
    {N_2N2P, {2, 2}},
    {N_P3HE, {0, 1, 0, 0, 1}},
    {N_D3HE, {0, 0, 1, 0, 1}},
    {N_3HEA, {0, 0, 0, 0, 1, 1}},
    {N_4N2P, {4, 2}},
    {N_4N2A, {4, 0, 0, 0, 0, 2}},
    {N_4NPA, {4, 1, 0, 0, 0, 1}},
    {N_3P, {0, 3}},
    {N_N3P, {1, 3}},
    {N_3N2PA, {3, 2, 0, 0, 0, 1}},
    {N_5N2P, {5, 2}},
  };
  for (const auto& c : cases)
    check(c.mt, c.channel);

  for (int mt :
    {MISC, N_LEVEL, N_FISSION, N_DISAPPEAR, N_XP, N_XD, N_XT, N_X3HE, N_XA}) {
    CHECK_FALSE(reaction_exit_channel(mt).has_value());
  }
}

TEST_CASE("ENDF discrete recoil levels")
{
  CHECK(is_discrete_level(N_N1));
  CHECK(is_discrete_level(N_N40));
  CHECK_FALSE(is_discrete_level(N_NC));

  for (auto bounds :
    {std::pair {N_P0, N_PC}, std::pair {N_D0, N_DC}, std::pair {N_T0, N_TC},
      std::pair {N_3HE0, N_3HEC}, std::pair {N_A0, N_AC}}) {
    CHECK(is_discrete_charged_level(bounds.first));
    CHECK(is_discrete_charged_level(bounds.second - 1));
    CHECK_FALSE(is_discrete_charged_level(bounds.second));
    CHECK(is_discrete_level(bounds.first));
  }
}

TEST_CASE("Generic Fisher-Yates shuffle")
{
  uint64_t seed = 17;
  int single[] {4};
  auto seed_before = seed;
  fisher_yates_shuffle(span<int> {}, &seed);
  fisher_yates_shuffle(span<int> {single, 1}, &seed);
  CHECK(seed == seed_before);
  CHECK(single[0] == 4);

  int first[] {0, 1, 2, 3, 4, 5};
  int second[] {0, 1, 2, 3, 4, 5};
  int original[] {0, 1, 2, 3, 4, 5};
  uint64_t first_seed = 12345;
  uint64_t second_seed = first_seed;
  fisher_yates_shuffle(span<int> {first, 6}, &first_seed);
  fisher_yates_shuffle(span<int> {second, 6}, &second_seed);
  CHECK(std::equal(std::begin(first), std::end(first), std::begin(second)));
  CHECK(std::is_permutation(std::begin(first), std::end(first),
    std::begin(original), std::end(original)));
  CHECK_FALSE(
    std::equal(std::begin(first), std::end(first), std::begin(original)));
}

TEST_CASE("Nuclear-number arithmetic")
{
  recoil::NuclearNumbers compound {26, 57};
  recoil::NuclearNumbers alpha {2, 4};
  auto daughter = compound - alpha;
  CHECK(daughter.Z == 24);
  CHECK(daughter.A == 53);
  CHECK(daughter.is_valid());
  daughter += alpha;
  CHECK(daughter.Z == compound.Z);
  CHECK(daughter.A == compound.A);
  CHECK_FALSE((recoil::NuclearNumbers {-1, 1}).is_valid());
  CHECK_FALSE((recoil::NuclearNumbers {3, 2}).is_valid());
}

TEST_CASE("Kalbach separation-energy systematics")
{
  // Independent evaluation of Kalbach's published liquid-drop expression for
  // 14 MeV neutron-induced alpha emission from Fe-56 at E_cm = 8 MeV.
  CHECK(recoil::kalbach_slope(14.0e6, 8.0e6, {2, 4}, 26, 56) ==
        Approx(0.720158564746175).epsilon(1.0e-12));
}

TEST_CASE("Kinematic contract: masses agree with the Python implementation")
{
  Fixture fx = read_fixture();
  REQUIRE(fx.found);
  REQUIRE(fx.masses.size() > 50);

  for (const auto& m : fx.masses) {
    double got = recoil::nuclear_mass_ev({m.z, m.a});
    INFO("Z=" << m.z << " A=" << m.a);
    REQUIRE(got > 0.0);
    REQUIRE(agrees(got, m.mass, m.mass));
  }
}

TEST_CASE("Light-ion spectrum agrees with the Python implementation")
{
  // Compared in log space. Below the barrier the density itself underflows to
  // zero in both languages, so comparing densities there would confirm only
  // that both underflowed. The finite log density tests the sub-barrier shape.
  Fixture fx = read_fixture();
  REQUIRE(fx.found);
  REQUIRE(fx.log_pdf.size() > 100);

  double worst = 0.0;
  for (const auto& r : fx.log_pdf) {
    double got =
      recoil::light_ion_log_pdf(r.e, r.e_max, r.z_b, r.a_b, r.z_d, r.a_d);
    INFO("Z_b=" << r.z_b << " A_b=" << r.a_b << " Z_d=" << r.z_d
                << " A_d=" << r.a_d << " E=" << r.e);
    REQUIRE(std::isfinite(got));
    // Relative in the log, so a density of 1e-300 is held to the same standard
    // as one of order unity. A discrepancy of 1e-10 in ln P is a 1e-10
    // relative discrepancy in the density itself. The tolerance accommodates
    // differences in association order for the square roots and softplus while
    // still detecting a drift in constants, masses, or expressions.
    worst = std::max(
      worst, std::fabs(got - r.log_p) / std::max(std::fabs(r.log_p), 1.0));
    REQUIRE(
      std::fabs(got - r.log_p) <= 1.0e-10 * std::max(std::fabs(r.log_p), 1.0));
  }
  INFO("worst relative disagreement in ln P: " << worst);
}

TEST_CASE("Kinematic contract: budgets and endpoints agree with Python")
{
  Fixture fx = read_fixture();
  REQUIRE(fx.found);
  REQUIRE(fx.cases.size() > 200);

  for (const auto& c : fx.cases) {
    INFO(c.name << " at E_in = " << c.e_in << " eV");

    auto q = recoil::mass_difference_q(
      {c.z_t, c.a_t}, span<const recoil::NuclearNumbers> {
                        c.emitted, static_cast<std::size_t>(c.n_emitted)});
    REQUIRE(q);
    REQUIRE(agrees(*q, c.q, c.e_in));

    // event endpoint: every other product is charged to the budget at rest, so
    // the ion recoils against the daughter plus the rest
    recoil::NuclearNumbers daughter {c.z_t, c.a_t + 1};
    double rest = 0.0;
    bool used_ion = false;
    for (int i = 0; i < c.n_emitted; ++i) {
      daughter.Z -= c.emitted[i].Z;
      daughter.A -= c.emitted[i].A;
      bool is_probe =
        !used_ion && c.emitted[i].Z == c.ion.Z && c.emitted[i].A == c.ion.A;
      if (is_probe)
        used_ion = true;
      else
        rest += recoil::nuclear_mass_ev(c.emitted[i]);
    }
    double m_b = recoil::nuclear_mass_ev(c.ion);
    double m_d = recoil::nuclear_mass_ev(daughter) + rest;
    double u0 = recoil::final_state_internal_energy(c.e_in, m_b + m_d, *q);
    REQUIRE(agrees(u0, c.u0, c.e_in));
    REQUIRE(agrees(recoil::two_body_endpoint(u0, m_b, m_d), c.e_event, c.e_in));

    REQUIRE(agrees(recoil::residual_excitation(u0, 0.5 * c.e_event, m_b, m_d),
      c.e_x, c.e_in));

    if (!(c.ion.Z == 0 && c.ion.A == 1)) {
      REQUIRE(agrees(recoil::shape_endpoint(c.e_in, {c.z_t, c.a_t}, c.ion),
        c.e_shape, c.e_in));
    }
  }
}

TEST_CASE("Kinematic contract: invariants hold independently of the fixture")
{
  // These would still have to hold if every stored number were wrong.
  const recoil::NuclearNumbers alpha {2, 4}, proton {1, 1}, neutron {0, 1};

  SECTION("an inelastic channel releases nothing")
  {
    for (auto target : {recoil::NuclearNumbers {6, 12}, {26, 56}, {82, 208}}) {
      auto q = recoil::mass_difference_q(
        target, span<const recoil::NuclearNumbers> {&neutron, 1});
      REQUIRE(q);
      REQUIRE(std::abs(*q) < 1.0e-3);
    }
  }

  SECTION("the final-state translation is what E_in + Q leaves out")
  {
    double m_final = recoil::nuclear_mass_ev({26, 55}) +
                     2.0 * recoil::nuclear_mass_ev(neutron);
    double u = recoil::final_state_internal_energy(14.0e6, m_final, -2.0e6);
    REQUIRE(u < 14.0e6 - 2.0e6);
    REQUIRE((14.0e6 - 2.0e6) - u ==
            Approx(14.0e6 * MASS_NEUTRON_EV / m_final).epsilon(1e-12));
  }

  SECTION("no excitation is left at the endpoint")
  {
    double m_b = recoil::nuclear_mass_ev(alpha);
    double m_d = recoil::nuclear_mass_ev({24, 53});
    double u = 9.0e6;
    double e_max = recoil::two_body_endpoint(u, m_b, m_d);
    REQUIRE(std::abs(recoil::residual_excitation(u, e_max, m_b, m_d)) < 1.0e-6);
  }

  SECTION("multi-neutron closure reserves the residual translation")
  {
    recoil::NuclearNumbers neutrons[2] {{0, 1}, {0, 1}};
    auto q = recoil::mass_difference_q(
      {26, 56}, span<const recoil::NuclearNumbers> {neutrons, 2});
    REQUIRE(q);

    double e_in = 14.0e6;
    double budget = e_in + *q;
    double e_out = 0.5 * (budget - 1.0);
    REQUIRE(2.0 * e_out <= budget);

    double m_n = MASS_NEUTRON * AMU_EV;
    double pz =
      std::sqrt(2.0 * m_n * e_in) + 2.0 * std::sqrt(2.0 * m_n * e_out);
    double m_r = recoil::nuclear_mass_ev({26, 55});
    double u = recoil::remaining_internal_energy(
      budget, 2.0 * e_out, {0.0, 0.0, pz}, m_r);
    REQUIRE(u < -0.5e6);
  }

  SECTION("a missing mass is reported, not invented")
  {
    REQUIRE(recoil::nuclear_mass_ev({60, 300}) == 0.0);
    auto q = recoil::mass_difference_q(
      {60, 300}, span<const recoil::NuclearNumbers> {&proton, 1});
    REQUIRE_FALSE(q);
    // an impossible daughter is caught too
    recoil::NuclearNumbers many[3] = {alpha, alpha, alpha};
    q = recoil::mass_difference_q(
      {2, 4}, span<const recoil::NuclearNumbers> {many, 3});
    REQUIRE_FALSE(q);
  }

  SECTION("the triton is the nucleus, not the H-3 atom")
  {
    // The shared mass API distinguishes atomic H-3 from the bare triton.
    double triton = recoil::nuclear_mass_ev({1, 3});
    REQUIRE(triton / AMU_EV == Approx(3.0155007).epsilon(1e-7));
    REQUIRE(triton / AMU_EV < 3.0160);
  }
}

TEST_CASE("Recoil particle masses")
{
  // Recoil kinematics always uses nuclear masses, even though the underlying
  // PDG-keyed table contains neutral-atom masses for these nuclides.
  REQUIRE(recoil::particle_mass_ev(ParticleType::photon()) == 0.0);
  REQUIRE(recoil::particle_mass_ev(ParticleType::electron()) ==
          Approx(MASS_ELECTRON * AMU_EV).epsilon(1e-12));
  REQUIRE(recoil::particle_mass_ev(ParticleType::neutron()) ==
          Approx(MASS_NEUTRON_EV).epsilon(1e-9));
  for (auto za : {recoil::NuclearNumbers {1, 1}, {1, 2}, {1, 3}, {2, 3}, {2, 4},
         {3, 7}, {26, 56}}) {
    ParticleType type = za.Z == 1 && za.A == 1 ? ParticleType::proton()
                                               : ParticleType {za.Z, za.A, 0};
    REQUIRE(recoil::particle_mass_ev(type) ==
            Approx(recoil::nuclear_mass_ev(za)).epsilon(1e-12));
  }
  REQUIRE(recoil::particle_mass_ev(ParticleType::triton()) / AMU_EV ==
          Approx(MASS_TRITON).epsilon(1e-13));
  REQUIRE(recoil::particle_mass_ev(ParticleType::triton()) / AMU_EV < 3.0160);

  // A nuclide that is not in the tabulated mass table still gets a usable mass
  double m = recoil::particle_mass_ev(ParticleType {40, 130, 0});
  REQUIRE(m > 0.0);
  REQUIRE(m / AMU_EV == Approx(130.0).epsilon(0.02));
}

TEST_CASE("Light-ion emission spectrum")
{
  // Alpha emission leaving Cr-53: the spectrum must vanish at both ends, be
  // strongly suppressed well below the Coulomb barrier, and integrate to a mean
  // that sits above the barrier.
  const double E_max = 13.3e6;
  const int Z_b = 2, A_b = 4, Z_d = 24, A_d = 53;

  REQUIRE(light_ion_pdf(0.0, E_max, Z_b, A_b, Z_d, A_d) == 0.0);
  REQUIRE(light_ion_pdf(E_max, E_max, Z_b, A_b, Z_d, A_d) == 0.0);
  REQUIRE(light_ion_pdf(2.0e6, E_max, Z_b, A_b, Z_d, A_d) <
          0.01 * light_ion_pdf(9.0e6, E_max, Z_b, A_b, Z_d, A_d));

  // Neutral light ions feel no barrier, so the spectrum is
  // E*(1 - E/E_max)^nu with the configured endpoint exponent.
  const recoil::LightIonParams params {};
  double neutral = light_ion_pdf(0.5 * E_max, E_max, 0, 1, Z_d, A_d);
  REQUIRE(
    neutral == Approx(0.5 * E_max * std::pow(0.5, params.nu)).epsilon(1e-12));

  SECTION("sampling reproduces the spectrum mean")
  {
    uint64_t seed = 1;
    const int N = 200000;
    double sum = 0.0;
    double max_sampled = 0.0;
    for (int i = 0; i < N; ++i) {
      double E = recoil::sample_light_ion_energy(
        E_max, E_max, Z_b, A_b, Z_d, A_d, &seed);
      REQUIRE(E >= 0.0);
      REQUIRE(E <= E_max);
      sum += E;
      max_sampled = std::max(max_sampled, E);
    }
    double sampled_mean = sum / N;

    // Reference mean by direct quadrature of the same pdf
    const int NQ = 200000;
    double num = 0.0, den = 0.0;
    for (int i = 0; i < NQ; ++i) {
      double E = E_max * (i + 0.5) / NQ;
      double f = light_ion_pdf(E, E_max, Z_b, A_b, Z_d, A_d);
      num += f * E;
      den += f;
    }
    REQUIRE(sampled_mean == Approx(num / den).epsilon(0.01));
    REQUIRE(max_sampled > 0.9 * E_max);
  }

  SECTION("truncation restricts the sample to the energy budget")
  {
    uint64_t seed = 7;
    const double E_limit = 4.0e6;
    for (int i = 0; i < 20000; ++i) {
      double E = recoil::sample_light_ion_energy(
        E_max, E_limit, Z_b, A_b, Z_d, A_d, &seed);
      REQUIRE(E <= E_limit);
      REQUIRE(E >= 0.0);
    }
  }
}

TEST_CASE("Light-ion spectrum: the endpoint exponent behaves as expected")
{
  // A larger nu must soften the spectrum, i.e. lower its mean. Preserve the
  // configured radius and dimensionless Gamow strength while varying nu.
  const recoil::LightIonParams params {};
  auto mean_of = [&](double nu) {
    recoil::LightIonParams par {params.r0, params.g, nu};
    const int N = 4000;
    double E_max = 10.0e6, num = 0.0, den = 0.0, prev_f = 0.0, prev_E = 0.0;
    for (int i = 0; i <= N; ++i) {
      double E = E_max * i / N;
      double f = light_ion_pdf(E, E_max, 1, 1, 26, 56, par);
      if (i > 0) {
        num += 0.5 * (f * E + prev_f * prev_E) * (E - prev_E);
        den += 0.5 * (f + prev_f) * (E - prev_E);
      }
      prev_f = f;
      prev_E = E;
    }
    return num / den;
  };
  REQUIRE(mean_of(2.0) < mean_of(1.0));
  REQUIRE(mean_of(1.0) < mean_of(0.5));
}

TEST_CASE("Light-ion spectrum: no exponent floor below the barrier")
{
  // Far below the barrier the log density must keep falling rather than
  // flattening to the E (1-E/E_max)^nu factor.
  const recoil::LightIonParams params {};
  const double E_max = 20.0e6;
  const int Z_b = 2, A_b = 3, Z_d = 74, A_d = 184; // He-3 on tungsten

  auto lp = [&](double E) {
    return recoil::light_ion_log_pdf(E, E_max, Z_b, A_b, Z_d, A_d, params);
  };
  REQUIRE(std::isfinite(lp(0.2e6)));
  REQUIRE(lp(0.2e6) < lp(0.4e6));
  REQUIRE(lp(0.4e6) < lp(0.8e6));
  // The barrier contribution makes the fall much steeper than the endpoint
  // factor alone, whose log change is under 1.5 here.
  REQUIRE(lp(0.4e6) - lp(0.2e6) > 5.0);

  // Far enough down, the direct form has nothing left. log p reaches -830 at
  // 20 keV, which is well past the -745 where exp() underflows to exactly
  // zero. The finite log density is therefore required to normalize this
  // region without changing its shape.
  REQUIRE(lp(2.0e4) < -745.0);
  REQUIRE(std::isfinite(lp(2.0e4)));
  REQUIRE(light_ion_pdf(2.0e4, E_max, Z_b, A_b, Z_d, A_d, params) == 0.0);
}

TEST_CASE("Light-ion sampler reproduces the spectrum it is given")
{
  // A distribution test, not a mean test. The sampler inverts a tabulated
  // cumulative, so the thing that can go wrong is the shape between table
  // points, which a mean is largely blind to.
  const recoil::LightIonParams params {};

  struct Case {
    const char* name;
    int Z_b, A_b, Z_d, A_d;
    double E_max, E_limit;
  };
  // every ion, light and heavy daughters, and a deeply truncated event
  const std::vector<Case> cases = {
    {"p on C-12", 1, 1, 6, 12, 9.0e6, 9.0e6},
    {"p on Fe-56", 1, 1, 26, 56, 11.0e6, 11.0e6},
    {"d on Fe-56", 1, 2, 26, 56, 8.0e6, 8.0e6},
    {"t on Nb-93", 1, 3, 41, 93, 6.0e6, 6.0e6},
    {"He-3 on Cr-52", 2, 3, 24, 52, 7.0e6, 7.0e6},
    {"alpha on Cr-53", 2, 4, 24, 53, 13.3e6, 13.3e6},
    {"alpha on W-184", 2, 4, 74, 184, 15.0e6, 15.0e6},
    {"alpha on W-184, truncated", 2, 4, 74, 184, 15.0e6, 4.0e6},
    {"p on U-238, deep truncation", 1, 1, 92, 238, 18.0e6, 0.6e6},
    {"neutral, no barrier", 0, 1, 26, 56, 10.0e6, 10.0e6},
  };

  for (const auto& c : cases) {
    INFO(c.name);

    // reference CDF by fine quadrature of the same log density
    const int NQ = 20000;
    std::vector<double> ref(NQ + 1, 0.0);
    double log_peak = -std::numeric_limits<double>::infinity();
    std::vector<double> f(NQ + 1);
    for (int i = 0; i <= NQ; ++i) {
      f[i] = recoil::light_ion_log_pdf(
        c.E_limit * i / NQ, c.E_max, c.Z_b, c.A_b, c.Z_d, c.A_d, params);
      log_peak = std::max(log_peak, f[i]);
    }
    REQUIRE(std::isfinite(log_peak));
    for (int i = 0; i <= NQ; ++i) {
      f[i] = std::isfinite(f[i]) ? std::exp(f[i] - log_peak) : 0.0;
    }
    for (int i = 1; i <= NQ; ++i) {
      ref[i] = ref[i - 1] + 0.5 * (f[i - 1] + f[i]);
    }
    REQUIRE(ref[NQ] > 0.0);
    for (auto& v : ref)
      v /= ref[NQ];

    // empirical CDF of the sampler on the same grid
    uint64_t seed = 20240814ULL;
    const int N = 200000;
    std::vector<int> hist(NQ, 0);
    double max_drawn = 0.0;
    for (int i = 0; i < N; ++i) {
      double E = recoil::sample_light_ion_energy(
        c.E_max, c.E_limit, c.Z_b, c.A_b, c.Z_d, c.A_d, &seed, params);
      REQUIRE(E >= 0.0);
      REQUIRE(E <= c.E_limit);
      int bin = std::min(static_cast<int>(E / c.E_limit * NQ), NQ - 1);
      ++hist[bin];
      max_drawn = std::max(max_drawn, E);
    }

    // Kolmogorov-Smirnov against the reference. The 99.9% critical value for
    // N = 2e5 is 1.95/sqrt(N) = 0.0044; allow a little more for the sampler's
    // own piecewise-linear approximation of the shape.
    double cum = 0.0, ks = 0.0;
    for (int i = 0; i < NQ; ++i) {
      cum += hist[i] / static_cast<double>(N);
      ks = std::max(ks, std::fabs(cum - ref[i + 1]));
    }
    REQUIRE(ks < 0.01);

    // No bin may contain a point mass inconsistent with the continuous CDF.
    int busiest = *std::max_element(hist.begin(), hist.end());
    REQUIRE(busiest < N / 20);

    // the sampled range reaches most of what is allowed
    REQUIRE(max_drawn > 0.5 * c.E_limit);
  }
}

TEST_CASE("Light-ion sampler is bounded and never fabricates a value")
{
  const recoil::LightIonParams params {};
  uint64_t seed = 7ULL;

  // A channel with no probability anywhere returns zero rather than a guess
  REQUIRE(recoil::sample_light_ion_energy(
            0.0, 0.0, 2, 4, 24, 52, &seed, params) == 0.0);
  REQUIRE(recoil::sample_light_ion_energy(
            -1.0, 1.0e6, 2, 4, 24, 52, &seed, params) == 0.0);

  // A limit above the endpoint is clipped to it, not honoured
  for (int i = 0; i < 1000; ++i) {
    double E = recoil::sample_light_ion_energy(
      5.0e6, 9.0e6, 2, 4, 24, 52, &seed, params);
    REQUIRE(E <= 5.0e6);
  }

  // Extreme truncation still samples inside the window and still produces a
  // distribution rather than a repeated value. It is *not* a wide
  // distribution: an alpha faces a 21 MeV barrier against W-184, so at a
  // kilovolt the spectrum climbs by hundreds of decades across the window and
  // everything piles up at the top. That is the physics, and the check is that
  // the draws are distinct, not that they are spread.
  for (double limit : {1.0e3, 1.0e4, 1.0e5}) {
    double lo = limit, hi = 0.0;
    int distinct = 0;
    double last_energy = -1.0;
    for (int i = 0; i < 2000; ++i) {
      double E = recoil::sample_light_ion_energy(
        15.0e6, limit, 2, 4, 74, 184, &seed, params);
      REQUIRE(E >= 0.0);
      REQUIRE(E <= limit);
      if (E != last_energy)
        ++distinct;
      last_energy = E;
      lo = std::min(lo, E);
      hi = std::max(hi, E);
    }
    REQUIRE(hi > 0.9 * limit);
    REQUIRE(hi > lo);
    REQUIRE(distinct > 1900);
  }
}
